name: "Itch.io Export"

on:
  workflow_run:
    workflows: ["godot-ci export"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Itch.io
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    strategy:
      matrix:
        platform: [windows, linux, mac]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: build/${{ matrix.platform }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Publish to Itch.io
        uses: XanatosX/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: ${{ matrix.platform }}
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: build/${{ matrix.platform }}
